# Generated by Django 4.2.28 on 2026-02-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=10),
        ),
        migrations.AddField(
            model_name='reminder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
