# Generated by Django 5.2.3 on 2026-02-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_reminder_type_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
